name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Test
      run: echo ${{ github.repository }}

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./build
        external_repository: ${{ github.repository }}
        publish_branch: gh-pages  
        allow_empty_commit: true